import { Plus } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { EmptyInline, PageIntro, TableSkeleton } from '../../components/ui'
import { supabase } from '../../lib/supabase'

export function Invoices({ orgId }: { orgId: string }) {
  const [rows, setRows] = useState<{ id: string; invoice_number: string; status: string; total: number; due_date: string | null; created_at: string }[]>([])
  const [form, setForm] = useState({ invoice_number: '', total: '', due_date: '' }); const [error, setError] = useState(''); const [busyId, setBusyId] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const load = useCallback(() => { supabase?.from('invoices').select('id,invoice_number,status,total,due_date,created_at').eq('organization_id', orgId).order('created_at', { ascending: false }).then(({ data }) => { setRows(data ?? []); setLoading(false) }) }, [orgId])
  useEffect(() => {
    // Opportunistically flags anything past its due date as OVERDUE each
    // time the page loads (there's no cron job wiring this up). A stale
    // status is only ever "not yet noticed", never wrong the other way --
    // this never marks something overdue before its actual due date.
    if (supabase) supabase.rpc('flag_overdue_invoices', { target_org: orgId }).then(() => load())
    else load()
  }, [orgId, load])
  async function add(event: React.FormEvent) { event.preventDefault(); if (!supabase) return; const { error: result } = await supabase.from('invoices').insert({ organization_id: orgId, invoice_number: form.invoice_number, total: Number(form.total), due_date: form.due_date || null }); if (result) setError(result.code === '23505' ? 'That invoice number already exists.' : result.message); else { setForm({ invoice_number: '', total: '', due_date: '' }); load() } }
  async function setStatus(id: string, status: string) { if (!supabase) return; setBusyId(id); const { error: result } = await supabase.from('invoices').update({ status }).eq('id', id).eq('organization_id', orgId); if (result) setError(result.message); else load(); setBusyId(null) }
  async function remind(id: string) { if (!supabase) return; setBusyId(id); const { error: result } = await supabase.rpc('send_invoice_reminder', { target_org: orgId, target_invoice: id }); if (result) setError(result.message); else setError(''); setBusyId(null) }
  const daysOverdue = (row: { due_date: string | null }) => row.due_date ? Math.floor((Date.now() - new Date(row.due_date).getTime()) / 86400000) : null
  return <div className="page"><PageIntro label="Invoices" title="Keep billing clear." description="Create simple invoice records in naira, track their status, and send a reminder when one is overdue." /><form className="panel record-form three" onSubmit={add}><div><label>Invoice number<input required value={form.invoice_number} onChange={(e) => setForm({ ...form, invoice_number: e.target.value })} placeholder="INV-0001" /></label></div><div><label>Total amount<input required type="number" min="0" value={form.total} onChange={(e) => setForm({ ...form, total: e.target.value })} placeholder="₦0.00" /></label></div><div><label>Due date (optional)<input type="date" value={form.due_date} onChange={(e) => setForm({ ...form, due_date: e.target.value })} /></label></div><button className="primary"><Plus size={16} /> Create draft</button>{error && <div className="form-error">{error}</div>}</form><section className="panel table-panel">{loading ? <TableSkeleton /> : rows.length ? <div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Status</th><th>Due date</th><th>Date</th><th>Total</th><th>Actions</th></tr></thead><tbody>{rows.map((row) => { const overdue = daysOverdue(row); return <tr key={row.id}><td><strong>{row.invoice_number}</strong></td><td><span className={`status ${row.status === 'PAID' ? 'completed' : row.status === 'OVERDUE' ? 'danger-text' : 'pending'}`}>{row.status}</span></td><td className={row.status === 'OVERDUE' && overdue != null ? 'warning-text' : ''}>{row.due_date ? new Date(row.due_date).toLocaleDateString('en-NG') : '—'}{row.status === 'OVERDUE' && overdue != null && overdue > 0 && <small className="field-help">{overdue} day{overdue === 1 ? '' : 's'} overdue</small>}</td><td>{new Date(row.created_at).toLocaleDateString('en-NG')}</td><td className="amount">₦{Number(row.total).toLocaleString('en-NG')}</td><td>{row.status === 'DRAFT' && <button type="button" className="text-btn" disabled={busyId === row.id} onClick={() => setStatus(row.id, 'SENT')}>Mark sent</button>}{(row.status === 'SENT' || row.status === 'OVERDUE') && <><button type="button" className="text-btn" disabled={busyId === row.id} onClick={() => setStatus(row.id, 'PAID')}>Mark paid</button><button type="button" className="text-btn" disabled={busyId === row.id} onClick={() => remind(row.id)}>Send reminder</button></>}{row.status !== 'PAID' && row.status !== 'CANCELED' && <button type="button" className="text-btn danger-text" disabled={busyId === row.id} onClick={() => setStatus(row.id, 'CANCELED')}>Cancel</button>}</td></tr> })}</tbody></table></div> : <EmptyInline title="No invoices yet" text="Create your first draft invoice above." />}</section></div>
}
