import { BookOpen, CreditCard, MessageCircle, Palette, Settings, ShieldCheck, UserRound } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { EmptyInline, PageIntro } from '../../components/ui'
import { normalizeLogoUrl } from '../../lib/format'
import { supabase } from '../../lib/supabase'
import { PasswordSettings } from '../auth/AuthScreens'

export function SettingsPage({ orgId, themeDark, onThemeChange, initialTab }: { orgId: string; themeDark: boolean; onThemeChange: (dark: boolean) => void; initialTab?: 'profile' | 'business' | 'billing' | 'appearance' | 'security' | 'feedback' | 'guide' }) {
  const [form, setForm] = useState({ name: '', tagline: '', address: '', phone: '', email: '', website: '', logo_url: '', receipt_prefix: '', tax_rate: '0' }); const [saved, setSaved] = useState(false); const [error, setError] = useState('')
  const [announcements, setAnnouncements] = useState<{ id: string; version: string; message: string; created_at: string }[]>([])
  const [activeTab, setActiveTab] = useState<'profile' | 'business' | 'billing' | 'appearance' | 'security' | 'feedback' | 'guide'>(initialTab ?? 'business')
  const [profileForm, setProfileForm] = useState({ full_name: '', phone: '' })
  const [profileMeta, setProfileMeta] = useState<{ email: string; createdAt: string } | null>(null)
  const [profileSaved, setProfileSaved] = useState(false); const [profileError, setProfileError] = useState(''); const [profileBusy, setProfileBusy] = useState(false)
  const loadProfile = useCallback(async () => {
    if (!supabase) return
    const { data: userData } = await supabase.auth.getUser()
    const user = userData.user
    if (!user) return
    setProfileMeta({ email: user.email ?? '', createdAt: user.created_at })
    const { data } = await supabase.from('profiles').select('full_name,phone').eq('id', user.id).maybeSingle()
    if (data) setProfileForm({ full_name: data.full_name ?? '', phone: data.phone ?? '' })
  }, [])
  useEffect(() => { if (activeTab === 'profile') void loadProfile() }, [activeTab, loadProfile])
  async function saveProfile(event: React.FormEvent) {
    event.preventDefault()
    if (!supabase) return
    setProfileBusy(true); setProfileError(''); setProfileSaved(false)
    const { data: userData } = await supabase.auth.getUser()
    const user = userData.user
    if (!user) { setProfileBusy(false); return }
    const { error: result } = await supabase.from('profiles').upsert({ id: user.id, full_name: profileForm.full_name.trim(), phone: profileForm.phone.trim() || null, updated_at: new Date().toISOString() })
    setProfileBusy(false)
    if (result) setProfileError(result.message)
    else { setProfileSaved(true); window.setTimeout(() => setProfileSaved(false), 2500) }
  }
  const [plans, setPlans] = useState<{ plan_id: string; code: string; name: string; description: string; trial_days: number; monthly_amount: number | null; currency: string; limits: Record<string, number | null> }[]>([])
  const [subscription, setSubscription] = useState<{ plan_id: string; status: string; trial_end: string | null; current_period_end: string | null } | null>(null)
  const [billingError, setBillingError] = useState(''); const [billingBusyPlan, setBillingBusyPlan] = useState('')
  const loadBilling = useCallback(() => {
    if (!supabase) return
    supabase.rpc('get_plan_catalog').then(({ data }) => setPlans((data ?? []) as typeof plans))
    supabase.from('subscriptions').select('plan_id,status,trial_end,current_period_end').eq('organization_id', orgId).maybeSingle().then(({ data }) => setSubscription(data))
  }, [orgId])
  useEffect(() => { loadBilling() }, [loadBilling])
  async function startTrial(planId: string) {
    if (!supabase) return
    setBillingBusyPlan(planId); setBillingError('')
    const { error: result } = await supabase.rpc('start_plan_trial', { target_org: orgId, target_plan: planId })
    if (result) setBillingError(result.message)
    else loadBilling()
    setBillingBusyPlan('')
  }
  const currentPlan = plans.find((plan) => plan.plan_id === subscription?.plan_id)
  const trialDaysLeft = subscription?.trial_end ? Math.max(0, Math.ceil((new Date(subscription.trial_end).getTime() - Date.now()) / 86400000)) : null
  const [feedbackRows, setFeedbackRows] = useState<{ id: string; category: string; severity: string; message: string; status: string; admin_response: string | null; created_at: string }[]>([])
  const [feedbackForm, setFeedbackForm] = useState({ category: 'feature_request', severity: 'medium', message: '' })
  const [feedbackBusy, setFeedbackBusy] = useState(false); const [feedbackError, setFeedbackError] = useState('')
  const loadFeedback = useCallback(() => { if (!supabase) return; supabase.from('product_feedback').select('id,category,severity,message,status,admin_response,created_at').eq('organization_id', orgId).order('created_at', { ascending: false }).then(({ data }) => setFeedbackRows(data ?? [])) }, [orgId])
  useEffect(() => { if (activeTab === 'feedback') loadFeedback() }, [activeTab, loadFeedback])
  async function submitFeedback(event: React.FormEvent) {
    event.preventDefault()
    if (!supabase || !feedbackForm.message.trim()) return
    setFeedbackBusy(true); setFeedbackError('')
    const userId = (await supabase.auth.getUser()).data.user?.id
    if (!userId) { setFeedbackBusy(false); return }
    const { error: result } = await supabase.from('product_feedback').insert({ organization_id: orgId, user_id: userId, category: feedbackForm.category, severity: feedbackForm.severity, message: feedbackForm.message.trim() })
    if (result) setFeedbackError(result.message)
    else { setFeedbackForm({ category: 'feature_request', severity: 'medium', message: '' }); loadFeedback() }
    setFeedbackBusy(false)
  }
  useEffect(() => { supabase?.from('organizations').select('name,tagline,address,phone,email,website,logo_url,receipt_prefix,tax_rate').eq('id', orgId).single().then(({ data }) => setForm({ name: data?.name ?? '', tagline: data?.tagline ?? '', address: data?.address ?? '', phone: data?.phone ?? '', email: data?.email ?? '', website: data?.website ?? '', logo_url: normalizeLogoUrl(data?.logo_url), receipt_prefix: data?.receipt_prefix ?? '', tax_rate: String(data?.tax_rate ?? 0) })) }, [orgId])
  useEffect(() => { supabase?.from('app_version_announcements').select('id,version,message,created_at').order('created_at', { ascending: false }).limit(20).then(({ data }) => setAnnouncements((data ?? []) as typeof announcements)) }, [])
  async function save(event: React.FormEvent) { event.preventDefault(); if (!supabase) return; setError(''); const payload = { ...form, tagline: form.tagline.trim() || null, receipt_prefix: form.receipt_prefix.toUpperCase(), tax_rate: Math.min(100, Math.max(0, Number(form.tax_rate) || 0)) }; const { error: result } = await supabase.from('organizations').update(payload).eq('id', orgId); if (result) setError(result.message); else { setForm({ ...form, tagline: form.tagline.trim(), receipt_prefix: payload.receipt_prefix, tax_rate: String(payload.tax_rate) }); setSaved(true) } }
  async function uploadLogo(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file || !supabase) return; if (!file.type.startsWith('image/')) { setError('Choose a PNG, JPG, WEBP, or SVG image.'); return } if (file.size > 2 * 1024 * 1024) { setError('Logo must be smaller than 2 MB.'); return } setError(''); const path = `${orgId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, '-')}`; const { error: uploadError } = await supabase.storage.from('business-logos').upload(path, file, { upsert: true, contentType: file.type }); if (uploadError) { setError(`Logo upload failed: ${uploadError.message}. Confirm the business-logos storage migration is applied.`); return } const { data } = supabase.storage.from('business-logos').getPublicUrl(path); setForm({ ...form, logo_url: normalizeLogoUrl(data.publicUrl) }); setSaved(false) }
  const tabs = [{ id: 'profile', label: 'My profile', icon: UserRound }, { id: 'business', label: 'Business profile', icon: Settings }, { id: 'billing', label: 'Billing', icon: CreditCard }, { id: 'appearance', label: 'Appearance', icon: Palette }, { id: 'security', label: 'Security', icon: ShieldCheck }, { id: 'feedback', label: 'Feedback', icon: MessageCircle }, { id: 'guide', label: 'Guide & updates', icon: BookOpen }] as const
  return <div className="page settings-page"><PageIntro label="Settings" title="Make it yours." description="Manage your business identity, workspace preferences, account security, and updates." /><nav className="settings-tabs" aria-label="Settings sections">{tabs.map(({ id, label, icon: Icon }) => <button key={id} type="button" className={`settings-tab ${activeTab === id ? 'active' : ''}`} aria-selected={activeTab === id} onClick={() => setActiveTab(id)}><Icon size={16} />{label}</button>)}</nav>
    {activeTab === 'profile' && <form className="panel settings-form" onSubmit={saveProfile}><div className="settings-section-heading"><span className="section-label">My profile</span><p className="muted">Your personal identity on this account — separate from the business profile.</p></div><label>Full name<input required value={profileForm.full_name} onChange={(e) => setProfileForm({ ...profileForm, full_name: e.target.value })} placeholder="Your name" /></label><label>Phone number<input type="tel" value={profileForm.phone} onChange={(e) => setProfileForm({ ...profileForm, phone: e.target.value })} placeholder="+234..." /></label><label>Email<input value={profileMeta?.email ?? ''} disabled /><small className="field-help">Contact support to change the email on your account.</small></label>{profileMeta?.createdAt && <p className="field-help">Member since {new Date(profileMeta.createdAt).toLocaleDateString('en-NG', { dateStyle: 'long' })}</p>}<div className="settings-actions"><button className="primary" disabled={profileBusy}>{profileBusy ? 'Saving…' : 'Save profile'}</button>{profileSaved && <span className="form-success">Saved.</span>}{profileError && <span className="form-error">{profileError}</span>}</div></form>}
    {activeTab === 'business' && <form className="panel settings-form" onSubmit={save}><div className="settings-section-heading"><span className="section-label">Business profile</span><p className="muted">Use real contact details. Your optional logo is shown in the receipt header.</p></div><label>Business name<input required minLength={2} value={form.name} onChange={(e) => { setForm({ ...form, name: e.target.value }); setSaved(false) }} /></label><label>Slogan (optional)<input maxLength={120} value={form.tagline} onChange={(e) => { setForm({ ...form, tagline: e.target.value }); setSaved(false) }} placeholder="e.g. Quality you can trust" /><small className="field-help">Shown under your business name on receipts. Leave blank to show nothing.</small></label><label>Address<input value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} placeholder="Street, city, state" /></label><label>Phone number<input type="tel" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} placeholder="+234..." /></label><label>Business email<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="hello@business.com" /></label><label>Website<input type="url" value={form.website} onChange={(e) => setForm({ ...form, website: e.target.value })} placeholder="https://business.com" /></label><label>Receipt prefix<input maxLength={8} pattern="[A-Za-z0-9]{2,8}" value={form.receipt_prefix} onChange={(e) => setForm({ ...form, receipt_prefix: e.target.value.toUpperCase() })} placeholder="ZB" /><small className="field-help">Used for receipt numbers such as ZB-001.</small></label><label>Tax / VAT rate (%)<input type="number" min="0" max="100" step="0.01" value={form.tax_rate} onChange={(e) => { setForm({ ...form, tax_rate: e.target.value }); setSaved(false) }} placeholder="7.5" /><small className="field-help">Applied to new sales going forward. Past receipts keep the rate that applied when they were created.</small></label><label className="settings-wide">Business logo (optional)<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={(e) => void uploadLogo(e)} /><small className="field-help">{form.logo_url ? 'Logo uploaded. Save the profile to use it on receipts.' : 'PNG, JPG, WEBP, or SVG up to 2 MB.'}</small></label><div className="settings-actions"><button className="primary">Save business profile</button>{saved && <span className="form-success">Saved to your organization.</span>}{error && <span className="form-error">{error}</span>}</div></form>}
    {activeTab === 'billing' && <><section className="panel settings-info billing-current"><span className="section-label">Current plan</span><h2>{currentPlan?.name ?? 'Free'}{subscription?.status === 'trialing' && <span className="version-badge">Trial</span>}</h2><p className="muted">{subscription?.status === 'trialing' && trialDaysLeft != null ? `${trialDaysLeft} day${trialDaysLeft === 1 ? '' : 's'} left in your trial. No card was charged to start it.` : subscription?.status === 'active' ? 'Your plan is active.' : subscription ? `Status: ${subscription.status}` : 'Loading your subscription…'}</p>{currentPlan && <ul className="billing-limits">{Object.entries(currentPlan.limits).map(([resource, limit]) => <li key={resource}><span>{resource.replace(/_/g, ' ')}</span><strong>{limit == null ? 'Unlimited' : limit.toLocaleString('en-NG')}</strong></li>)}</ul>}<p className="field-help">Online payments aren't connected yet — plan changes here are trial-only. Contact support to arrange a paid plan in the meantime.</p></section>{billingError && <div className="form-error" role="alert">{billingError}</div>}<section className="panel"><span className="section-label">Available plans</span><h2>Compare and start a trial.</h2><div className="billing-plan-grid">{plans.map((plan) => <div key={plan.plan_id} className={`billing-plan-card ${currentPlan?.plan_id === plan.plan_id ? 'billing-plan-current' : ''}`}><strong>{plan.name}</strong><span className="amount">{plan.monthly_amount ? `₦${Number(plan.monthly_amount).toLocaleString('en-NG')}/mo` : plan.code === 'enterprise' ? 'Custom pricing' : 'Free'}</span><p className="muted">{plan.description}</p>{currentPlan?.plan_id === plan.plan_id ? <span className="status completed">Current plan</span> : plan.code === 'enterprise' ? <button type="button" className="secondary" disabled>Contact support</button> : <button type="button" className="secondary" disabled={billingBusyPlan === plan.plan_id || subscription?.status === 'trialing'} onClick={() => void startTrial(plan.plan_id)}>{billingBusyPlan === plan.plan_id ? 'Starting…' : plan.trial_days > 0 ? `Start ${plan.trial_days}-day trial` : 'Switch to this plan'}</button>}</div>)}</div></section></>}
    {activeTab === 'appearance' && <section className="panel settings-preferences"><div><span className="section-label">Preferences</span><h2>Make the workspace comfortable.</h2><p>These settings are saved on this device and do not change your business records.</p></div><label className="settings-toggle-row"><span><strong>Dark mode</strong><small>Use the dark Zerøbyte workspace theme.</small></span><input type="checkbox" role="switch" checked={themeDark} onChange={(event) => onThemeChange(event.target.checked)} /></label></section>}
    {activeTab === 'feedback' && <><section className="panel"><span className="section-label">Tell us what's not working (or what would help)</span><h2>Send feedback.</h2><form className="record-form" onSubmit={submitFeedback} style={{ marginTop: 16 }}><label>Category<select value={feedbackForm.category} onChange={(e) => setFeedbackForm({ ...feedbackForm, category: e.target.value })}><option value="bug">Bug</option><option value="ux">Something's confusing</option><option value="feature_request">Feature request</option><option value="performance">Performance</option><option value="billing">Billing</option><option value="documentation">Documentation</option><option value="integration">Integration</option></select></label><label>Severity<select value={feedbackForm.severity} onChange={(e) => setFeedbackForm({ ...feedbackForm, severity: e.target.value })}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical — blocking my work</option></select></label><label className="form-wide">What happened?<textarea required value={feedbackForm.message} onChange={(e) => setFeedbackForm({ ...feedbackForm, message: e.target.value })} placeholder="The more detail the better." /></label>{feedbackError && <div className="form-error">{feedbackError}</div>}<button className="primary" disabled={feedbackBusy}>{feedbackBusy ? 'Sending…' : 'Send feedback'}</button></form></section><section className="panel table-panel"><div className="panel-heading"><div><span className="section-label">Your reports</span><h2>{feedbackRows.length} submitted</h2></div></div>{feedbackRows.length ? <div className="table-wrap"><table><thead><tr><th>Category</th><th>Severity</th><th>Message</th><th>Status</th><th>Response</th><th>Date</th></tr></thead><tbody>{feedbackRows.map((row) => <tr key={row.id}><td>{row.category.replace(/_/g, ' ')}</td><td>{row.severity}</td><td style={{ maxWidth: 260 }}>{row.message}</td><td><span className={`status ${row.status === 'resolved' ? 'completed' : row.status === 'declined' ? 'refunded' : 'pending'}`}>{row.status}</span></td><td>{row.admin_response || '—'}</td><td>{new Date(row.created_at).toLocaleDateString('en-NG')}</td></tr>)}</tbody></table></div> : <EmptyInline title="No feedback sent yet" text="Anything you report here goes straight to the team." />}</section></>}
    {activeTab === 'security' && <><section className="panel settings-security"><span className="section-label">Account security</span><h2>Change your password</h2><p>Choose a unique password you do not reuse elsewhere.</p><PasswordSettings /></section><section className="panel settings-info"><span className="section-label">Data protection</span><h2>Organization-scoped by default.</h2><p>Every product, customer, sale and expense is protected by Supabase Row Level Security and tied to this workspace.</p></section></>}
    {activeTab === 'guide' && <><section className="panel app-version-card"><div><span className="section-label">Application</span><h2>Zerøbyte Business <span className="version-badge">v{import.meta.env.VITE_APP_VERSION ?? '1.0.0'}</span></h2><p className="muted">{announcements[0] ? `Latest release · v${announcements[0].version}: ${announcements[0].message}` : 'You are running the current published workspace.'}</p></div></section>{announcements.length > 0 && <section className="panel changelog-panel"><div className="panel-heading"><div><span className="section-label">Release history</span><h2>Changelog</h2></div><span className="version-badge">{announcements.length} release{announcements.length === 1 ? '' : 's'}</span></div><div className="changelog-list">{announcements.map((item) => <article className="changelog-entry" key={item.id}><div><strong>v{item.version}</strong><time>{new Date(item.created_at).toLocaleDateString('en-NG', { dateStyle: 'medium' })}</time></div><p>{item.message}</p></article>)}</div></section>}<section className="panel settings-info"><span className="section-label">User guide</span><h2>A simple rhythm for clean records.</h2><div className="guide-list"><p><strong>1. Inventory:</strong> add products and receive stock. Stock intake is recorded automatically.</p><p><strong>2. Sales:</strong> choose a customer first, add products, then complete the sale.</p><p><strong>3. Expenses:</strong> record operating costs on the Expenses page.</p><p><strong>4. Records:</strong> choose a period to review history, totals, and export CSV for Excel or Sheets. Records are read-only here.</p><p><strong>5. Offline:</strong> drafts and queued changes stay on this device until you reconnect. Review the sync banner before signing out.</p></div></section></>}
  </div>
}
